version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-south-1:860061945305:task-definition/swadesh-process-pension-task:1"
        LoadBalancerInfo:
          ContainerName: "swadesh-process-pension-container"
          ContainerPort: "8084"
        PlatformVersion: "LATEST"
